FROM ubuntu

MAINTAINER André Roque Matheus <amatheus@mac.com>

RUN apt-get update; apt-get -y upgrade

RUN apt-get -y install curl build-essential

RUN curl https://sh.rustup.rs -sSf | sh -s -- -y

ENV PATH=/root/.cargo/bin:$PATH
